### ISSUE TITLE
Tooltips are black when using dkfds-tippy-theme.standalone.css

### ISSUE THREAD

**Issue by 4nd3r5** [detfaellesdesignsystem/dkfds-components#105]
**Bekskriv fejlen (Describe the bug)**
Tooltips are black in the plugin version of the tippy tooltip and they have an arrow. 

**Indsæt link (Add a URL)**
https://github.com/detfaellesdesignsystem/dkfds-plugins/blob/fa0449c877d6d85ee5314ccec6a2491eed16ba2f/dist/css/dkfds-tippy-theme.standalone.css#L587

**Screenshots**
Before plugin ,where we use dkfds-js:
![image](https://user-images.githubusercontent.com/19467082/76515637-33603a00-645a-11ea-872e-b7439859c2f4.png)

After replacing with the plugin
![image](https://user-images.githubusercontent.com/19467082/76515516-fc8a2400-6459-11ea-822b-9ecdbadf4d1d.png)

**Comment by detfaellesdesignsystem** [comment]
Hi @4nd3r5,

Version 6.0.1 has been released with a fix.

We needed to upgrade our support for Tippy.js since the last tested version was v4.3.5.

We now support Tippy.js v6.1.0 including the old 4.3.5 version.

Be aware the new version of Tippy.js needs a polyfill for Internet Explorer.

Best regards,
Kristina Jensen
Det Fælles Designsystem
